
[env]
ALACRITTY_CONFIG = "~/.config/alacritty/alacritty.toml"
AWESOME_CONFIG = "~/.config/awesome/rc.lua"
BASH_CONF = "~/.bashrc"



[window]
padding = { x = 15, y = 15 }
decorations = "None"
opacity = 0.9
blur = true

[font]
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
bold = { family = "0xProto Nerd Font Mono", style = "Bold" }
italic = { family = "0xProto Nerd Font Mono", style = "Italic" }

# Default colors
[colors.primary]
background = '#171d23'
foreground = '#ffffff'

# Cursor colors
[colors.cursor]
text   = '#fafafa'
cursor = '#008b94'

# Normal colors
[colors.normal]
black   = '#333f4a'
red     = '#d95468'
green   = '#8bd49c'
blue    = '#539afc'
magenta = '#b62d65'
cyan    = '#70e1e8'
white   = '#b7c5d3'

# Bright colors
[colors.bright]
black   = '#41505e'
red     = '#d95468'
green   = '#8bd49c'
yellow  = '#ebbf83'
blue    = '#5ec4ff'
magenta = '#e27e8d'
cyan    = '#70e1e8'
white   = '#ffffff'

[cursor.style]
shape = "Block"
blinking = "On"

[selection]
save_to_clipboard = true
